apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-review.fullname" . }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ include "movie-review.name" . }}
  template:
    metadata:
      labels:
        app: {{ include "movie-review.name" . }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ include "movie-review.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
