apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "movie-review.fullname" . }}
  labels:
    {{- include "movie-review.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "movie-review.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "movie-review.selectorLabels" . | nindent 8 }}
    spec:
      imagePullSecrets:
        - name: regcred
      containers:
        - name: {{ include "movie-review.name" . }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.port }}
          env:
            {{- range $k, $v := .Values.env }}
            - name: {{ $k }}
              value: "{{ $v }}"
            {{- end }}
