replicaCount: 1

image:
  repository: 197315783820.dkr.ecr.ap-southeast-1.amazonaws.com/movie-review
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 5000

ingress:
  enabled: false
  hosts:
    - host: jamidvp.movie-review.site
      paths:
        - /
service:
  type: NodePort
  port: 5000
  targetPort: 5000     # Your app container port
  nodePort: 30050      # Any port between 30000â€“32767

resources: {}
env: {}
